# Generated by Django 4.2.7 on 2023-12-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart_item',
            table='Cartitem',
        ),
    ]
