# Generated by Django 4.2.7 on 2023-12-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_item_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart_item',
            table='Cart_item',
        ),
    ]
